Repository moul/assh, pull requests merged in 2022-05, with the labels that each got.

#525 feat(config): Make HostKeyAlgorithms also a slice
  Makefile
  README.md
  pkg/config/config_test.go
  pkg/config/host.go
  pkg/config/host_test.go
Labels: Enhancement, ✅ Approved

#526 feat(config): Add ProxyJump
  pkg/config/config_test.go
  pkg/config/host.go
  pkg/config/host_test.go
Labels: Enhancement, 🔍 Ready for Review

#528 test(ci): test on go1.18
  .github/workflows/ci.yml
Labels: 🔍 Ready for Review, test
